In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.45575686, 0.33907896, 0.53653838, 0.83691453, 0.23981827])

In [21]:
np.random.randn(2)

array([ 0.14128457, -1.32197959])

In [22]:
np.random.randint(1, 100)

83

In [23]:
np.random.randint(1, 100, 10)

array([63, 20, 56, 27, 69, 74, 67, 32, 40, 17])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([42,  0,  4, 15, 44, 30, 19, 25, 32, 17])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

44

In [31]:
ranarr.min()

0

In [32]:
ranarr.argmax()

4

In [33]:
ranarr.argmin()

1

In [34]:
arr.shape

(25,)

In [35]:
arr = arr.reshape(5,5)

In [36]:
arr.shape

(5, 5)

In [37]:
arr.dtype

dtype('int32')

In [38]:
arr = np.arange(0,11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[8]

8

In [41]:
arr[1:5]

array([1, 2, 3, 4])

In [42]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [43]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [44]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
arr[0:5] = 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr = arr[0:6]

In [50]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_arr[:] = 99

In [52]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
arr_copy = arr.copy()

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy[:] = 100

In [57]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [58]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [59]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d[0]

array([ 5, 10, 15])

In [61]:
arr_2d[2][1]

40

In [62]:
arr_2d[1,2]

30

In [63]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [64]:
arr = np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
bool_arr = arr > 5

In [68]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [69]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [70]:
arr[arr<3]

array([1, 2])

In [71]:
arr_2d = np.arange(50).reshape(5,10)

In [72]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [73]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])