In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.45575686, 0.33907896, 0.53653838, 0.83691453, 0.23981827])

In [21]:
np.random.randn(2)

array([ 0.14128457, -1.32197959])

In [22]:
np.random.randint(1, 100)

83

In [23]:
np.random.randint(1, 100, 10)

array([63, 20, 56, 27, 69, 74, 67, 32, 40, 17])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([42,  0,  4, 15, 44, 30, 19, 25, 32, 17])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

44

In [31]:
ranarr.min()

0

In [32]:
ranarr.argmax()

4

In [33]:
ranarr.argmin()

1

In [34]:
arr.shape

(25,)

In [35]:
arr = arr.reshape(5,5)

In [36]:
arr.shape

(5, 5)

In [37]:
arr.dtype

dtype('int32')